name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Make test files executable
      run: |
        chmod +x tests/*.zsh
        find lib -name "*.zsh" -type f -exec chmod +x {} \;
        chmod +x scripts/*.zsh
        chmod +x z-skk.plugin.zsh
    
    - name: Install zsh
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          sudo apt-get update
          sudo apt-get install -y zsh
        fi
        # macOS has zsh pre-installed
    
    - name: Show zsh version
      run: zsh --version
    
    - name: Show directory structure
      run: |
        echo "=== Directory structure ==="
        ls -la
        echo "=== lib directory ==="
        ls -la lib/ || echo "lib directory not found"
        echo "=== lib subdirectories ==="
        find lib -type d -name "*" | head -20
    
    - name: Run tests
      run: |
        zsh tests/test_plugin_loading.zsh
        zsh tests/test_zinit_loading.zsh
    
    - name: Run all tests
      shell: bash
      run: |
        if [[ -f tests/run_all.zsh ]]; then
          zsh tests/run_all.zsh
        fi

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run shellcheck on zsh files
      shell: bash
      run: |
        echo "Skipping shellcheck for zsh files (shellcheck doesn't fully support zsh syntax)"
        # TODO: Consider using a zsh-specific linter in the future
    
    - name: Check file permissions
      shell: bash
      run: |
        # Ensure script files are executable
        find . -name "*.zsh" | while read -r file; do
          if [[ ! -x "$file" ]]; then
            echo "Warning: $file is not executable"
          fi
        done
    
    - name: Check for trailing whitespace
      run: |
        if grep -r '[[:space:]]$' --include="*.zsh" .; then
          echo "Error: Found trailing whitespace"
          exit 1
        fi
    
    - name: Check for tabs vs spaces consistency
      shell: bash
      run: |
        # We use spaces for indentation
        if grep -r $'^\t' --include="*.zsh" .; then
          echo "Warning: Found tabs used for indentation (should use spaces)"
        fi